[[Powsybl]]
arch = "aarch64"
git-tree-sha1 = "ab034887526e750628adf3fba2d980013018c69a"
julia_version = "1.10.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "a1af2ed24a439b2df55cc916bc41df55a90e2830d6e07e5b6742e3fd6cb1201d"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[Powsybl]]
arch = "aarch64"
git-tree-sha1 = "319cba5640181b3d9928c7d264f307e4364e7769"
julia_version = "1.11.1"
os = "macos"

    [[Powsybl.download]]
    sha256 = "e6550012f16289574b05be77f58203530814f86de8fb8299842677438458c308"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[Powsybl]]
arch = "aarch64"
git-tree-sha1 = "c3a8baa23ad3a2953533cb15c5f5279425546151"
julia_version = "1.12.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "5fc660a738e3738ea17b7e6d5817aa5dfd29cb4b441b88e165f19c184996228d"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[Powsybl]]
arch = "aarch64"
git-tree-sha1 = "a10293911f72a4b8db551c514e334dbf89b59e78"
julia_version = "1.13.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "08ab895749b244e93af461f344e75069f0527bae8288dedd8be292abb92a5096"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[Powsybl]]
arch = "aarch64"
git-tree-sha1 = "9be6bbb5942a8ed3e7766f57b1e314e58aaf718b"
julia_version = "1.14.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "bee0b4807093ee06a8677596670a693ce409259ddaa4952b2c72583911c4f1f2"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.aarch64-apple-darwin-julia_version+1.14.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
git-tree-sha1 = "6f0094f3c305890c462df27ece42dc2276a2fbe0"
julia_version = "1.10.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "87224e6b37d17f2d1110b58f1f2d6724b94a1cec864e53e9718605f019fdfcd0"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
git-tree-sha1 = "c4971cbf93aeba91aa9e32fb2d7cece61e4a413e"
julia_version = "1.11.1"
os = "macos"

    [[Powsybl.download]]
    sha256 = "38577d9b90f343169f8e0a98feb700bd9466d4f029e09b1e7c8cafe59f80d93f"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[Powsybl]]
arch = "x86_64"
git-tree-sha1 = "566b3f7f86dbadab312505d7405ab5e72f5166f5"
julia_version = "1.12.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "ddb5b3783008ea6652f9a50a1f2f6b98eadb4ec2476b4381a697236c4c2ff56a"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
git-tree-sha1 = "ee0e4d91fe86be50e39db3e06b10c49fb4e9972a"
julia_version = "1.13.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "ecdccaf92370306e50c8e8f3fc70c8b18cfcad46b0e8d3e0220c400218e08120"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
git-tree-sha1 = "872243f9dd26b69dd4fdf2c1609100d82b47446b"
julia_version = "1.14.0"
os = "macos"

    [[Powsybl.download]]
    sha256 = "3d5ccdbc9be00c64adc46e6cbc9f563bdd253a5f85e23798591bf1da3ac00b2c"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-apple-darwin-julia_version+1.14.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d48680565e206ba39268700ea6585db2b641b09"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[Powsybl.download]]
    sha256 = "a1cdf50288ec040512a1f3b15ed2aa518aa54f568eaa0cc916d56513a2ec4909"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d6a07aef8a6e395f1c0f6b0a80567a90fec7273"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[Powsybl.download]]
    sha256 = "50f3f3c83a57799e77f453998596c41e58de55396ef309ba43f2d4f55a29e5b2"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7359a18b5a1225d9196f5927bb885c598d2411a"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[Powsybl.download]]
    sha256 = "c19da6b5308413f1447e5eae1a33edf2fd64fb5dbb830701d598366cf4926511"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "368e0702ab403e19b695951ee6e2eba189ea4773"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[Powsybl.download]]
    sha256 = "b3ea6e7a4f2f9b4f6575e133d9d8b97a99a1931061f369b635747b6cccd03dde"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "716a7e95182d5227449b70e48bbce4d024fa9321"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[Powsybl.download]]
    sha256 = "44095ad718bede88bde05a0ab91734fb31a9172e457ba7581b7890ff7ac45b49"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31158b0a802fc3c41f6cdc9c06be2f84a005697d"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[Powsybl.download]]
    sha256 = "aa943fefd3d1c2017e132f2232faa36bf29ce7179dd8e5a4190a129b75eaf8d3"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-musl-cxx11-julia_version+1.10.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc051d2f38f2db1e70bf5eea37a0e77959c52bb3"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[Powsybl.download]]
    sha256 = "b20c7d5321d395a906173da28e0a96f8abc4806295e313d407572b006e88d234"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c9c6fd3b12f30db89030161c7681bd39fbc02a7"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[Powsybl.download]]
    sha256 = "310231875cf7133560ec00d4ef7e526f0a4aca1ddf17f83bf138f7dca7f865fd"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7aa8a1bf9925e2931e1d7d43564e5a2e1e368be3"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[Powsybl.download]]
    sha256 = "fdc82b5bbf47867c09f69b37bfdaac58db6a20547781768a82c689e3d4efd1e0"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-musl-cxx11-julia_version+1.13.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6a9bbc98ba51d88410a80d6cda25bd7644ddae2"
julia_version = "1.14.0"
libc = "musl"
os = "linux"

    [[Powsybl.download]]
    sha256 = "0fb8c56fa2055555f571c5f01ed8bc1caf889ba12533d2039845cccb89fa7a8d"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-linux-musl-cxx11-julia_version+1.14.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29e492e27f92d656e273c237b0f6efbb5e213e70"
julia_version = "1.10.0"
os = "windows"

    [[Powsybl.download]]
    sha256 = "1e48f5f3f718cc7ccd22da1f1e0a140fdfd14df970b9e9250d5c0c0c25168ed4"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b463b572458f3e9aa88710ecc2b37800f7b2dcc"
julia_version = "1.11.1"
os = "windows"

    [[Powsybl.download]]
    sha256 = "984f248189c555544c12afc4c9a92a29a23e39a9d2bf564b31a849acd775b144"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7471f25ade7b31fe55d3ddf3b43b00afe8f8062"
julia_version = "1.12.0"
os = "windows"

    [[Powsybl.download]]
    sha256 = "9b8e28d0043fb301392c8affcb1aa07cd67cf9ebe45866209ce052b8e525bea0"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42b863c229a7e024d396b7f3ffa95112c17c6347"
julia_version = "1.13.0"
os = "windows"

    [[Powsybl.download]]
    sha256 = "5558b55ab0818e1e1a09ef867fd3f06fdc960a6240c005a22b881e54af5e48b0"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[Powsybl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42b863c229a7e024d396b7f3ffa95112c17c6347"
julia_version = "1.14.0"
os = "windows"

    [[Powsybl.download]]
    sha256 = "5558b55ab0818e1e1a09ef867fd3f06fdc960a6240c005a22b881e54af5e48b0"
    url = "https://github.com/JuliaBinaryWrappers/Powsybl_jll.jl/releases/download/Powsybl-v0.3.0+0/Powsybl.v0.3.0.x86_64-w64-mingw32-cxx11-julia_version+1.14.0.tar.gz"
